### ISSUE TITLE
Add algorithm for automatic group matching

### ISSUE THREAD

**Issue by happyiminjay1** [dksehdals216/Histudy#4]
Group matching system

같이 스터디 하고 싶은 멤버 지정
a) 인원수 충원 필요

1지망 과목 같은 분반/교수님 (영어 수업 확인 필요)
a) 동일 교수님 일시 영어/한국어 분반 무시

1,2,3 지망 안맞을 경우 1지망 맞을시 과목이 많은 위주로 매칭
a) 옵션에 따라 변경 가능

유동적 매칭 필요
a) 1,2 지망이 DS, JAVA
1, 2 JAVA, DS
일 경우, 교수님이 동일하기 때문에 같이 매칭

**Comment by dksehdals216** [comment]
Completed by @wooseokyourself  and @binarywoo27
